name: GH Pages Gatsby Publish

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
#      - run: npm run format
#      - run: npm run test
      - run: npm run build-dev

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          external_repository: itsrobli/co-robli-dev
#          cname: github.com